services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.14.2
    ports:
      - 9200:9200
    environment:
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      ELASTIC_HOST: elasticsearch
      discovery.type: single-node

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      GRAFANA_HOST: grafana
      GF_SECURITY_ADMIN_USER: user
      GF_SECURITY_ADMIN_PASSWORD: user

  kibana:
    container_name: kibana
    image: kibana:7.14.2
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
